### ISSUE TITLE
Crawler seems broken

### ISSUE THREAD

**Issue by tlindener** [Jhruzik/crawler_immoscout_GER#1]
Hi, unfortunately it looks like they changed the website and the crawler isn't working anymore. I tried to adjust the link search like this:
```
        link_list_raw = []
        for option in site_extract.find_all("a",{"class":"result-list-entry__brand-title-container"}):
            print(option["href"])
            link_list_raw.append(option["href"])
```
The problem i though, that additional results are probably loaded via javascript because with this I only get a couple of expose ids

**Comment by mmbader** [comment]
I noticed the same thing, did not work for me either. I rewrote parts of the script to make it work again, feel free to use and adjust it. Sorry, I am still quite new to Python and Github, what is the best way to share this with the community? Create a fork? Sorry for being a newb ;-)

Cheers,
Michael

---

# %load immoscrap.py
from urllib.request import urlopen
from urllib.error import HTTPError
from urllib.error import URLError
from bs4 import BeautifulSoup
from pandas import DataFrame
import numpy as np
import re

suffix = ["Wohnung-Miete", "Haus-Miete", "Wohnung-Kauf", "Haus-Kauf"]
prefix = "https://www.immobilienscout24.de/Suche/S-T/"
wohnung_data = DataFrame()


def get_links(category):
    try:
        url = urlopen(prefix + category)
    except:
        print("Fehler beim Oeffnen der Website")
    try:
        site_extract = BeautifulSoup(url.read(), "lxml")
    except Exception as e: print("Fehler beim Einlesen in BeautifulSoup:\n" + str(e))
    try:
        options_min_max = []
        for option in site_extract.find_all("option"):
            options_min_max.append(option["value"])
    except:
        print("Fehler beim Loop")
    try:
        link_list = np.arange(1, int(options_min_max[1]) + 1)
    except Exception as e: print("Fehler beim Erstellen der Link Liste:\n" + str(e))
    else:
        return link_list

    
def get_data(url):
    try:
        url_raw = url
        url = urlopen(url)
    except HTTPError as e:
        return None
    except URLError as e:
        return None
    try:
        site_extract = BeautifulSoup(url.read(), "lxml")
        rawdata_extract = site_extract.find_all("div", {"class":"result-list-entry__data"})
    except AttributeError as e:
        return None
    global wohnung_data
    price = []
    size = []
    rooms = []
    location = []
    ownership = []
    immo_type = []
    expose = []
    for i in range(1,len(rawdata_extract)):
        try:
            price.append(rawdata_extract[i].find_all("dd")[0].get_text().strip())
        except:
            price.append(None)
        try:
            size.append(rawdata_extract[i].find_all("dd")[1].get_text().strip())
        except:
            size.append(None)
        try:
            rooms.append(rawdata_extract[i].find_all("dd")[2].get_text().strip())
        except:
            rooms.append(None)
        try:
            location.append(rawdata_extract[i].find_all("div", {"class":"result-list-entry__address"})[0].get_text().strip())
        except:
            location.append(None)
        try:
            expose.append(str(rawdata_extract[i]).split("data-result-id",1)[1].split("\"",2)[1])
        except:
            expose.append(None)
        if "/Wohnung" in url_raw:
            immo_type.append("Wohnung")
        elif "/Haus" in url_raw:
            immo_type.append("Haus")
        if "-Miete" in url_raw:
            ownership.append("Miete")
        elif "-Kauf" in url_raw:
            ownership.append("Kauf")
    wohnung_data = wohnung_data.append(DataFrame({"price":price, "size":size, "rooms":rooms, "location":location, "expose":expose, "real_estate":immo_type, "ownership":ownership}), ignore_index=True)
    
def immo_crawl(suffix, sample='N'):
    for category in suffix:
        link_list = get_links(category)
        for link in link_list:
            print("Bearbeiten der Seite " + str(link) + " der Kategorie " + category)
            get_data(prefix + "P-" + str(link) + "/" + category)
            if sample == 'Y':
                if link == 1:
                    break

---

Then you can use the following commands. If you just want to see if you get results, use sample = 'Y':

immo_crawl(suffix, sample='Y')
wohnung_data.to_csv("wohnung_data_raw_mb.csv", sep=";", index=False)

**Comment by Jhruzik** [comment]
Thank you for pointing out! I assumed that they would adjust the site at some point. Also thank you for also suggesting a fix.

I will look into it and do the adjustments in the near future (while I am at it, I'll also add some comment. After half a year it now haunts me).

Thank you again!
Joshua

**Comment by Jhruzik** [comment]
I made all necessary changes and it does work again. I also tweaked the code somewhat and added a performance indicator. Note that from now on, the data will be saved inside your scripts directory. 

Thanks again for pointing out!
